{
 "title": "Java Memory",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Initial Java Memory",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pool) (max by(pool) (runtime_java_memory_init_size_bytes{service_name=\"jheapusage\"}))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Used Java Memory",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pool) (max by(pool) (runtime_java_memory_used_bytes{service_name=\"jheapusage\"}))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Committed Java Memory",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pool) (max by(pool) (runtime_java_memory_committed_bytes{service_name=\"jheapusage\"}))",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Maximum Java Memory",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pool) (max by(pool) (runtime_java_memory_max_size_bytes{service_name=\"jheapusage\"}))",
     "legendFormat": "{{ pool }}"
    }
   ]
  }
 ]
}